name: tech_smart_shop
description: "TechSmart Shop - Electrical & Technology Marketplace."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^10.3.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/techsmart_shop_logo.png
    - assets/branding/techsmart_shop_app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/techsmart_shop_app_icon.png
  remove_alpha_ios: true

